import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Tugas Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="lg:grid flex flex-col grid-cols-[1fr_15fr] bg-gray-100 min-h-screen">
        {/* Sidebar kiri */}
        <div className="hidden lg:flex w-20 hover:w-64 smooth">
          <Sidebar />
        </div>
        <div className="w-fit flex lg:hidden">
          <Navbar/>

        </div>

        {/* Main Content */}
        <main className="px-5 py-7 lg:m-[1%]  mt-[15%] smooth">{children}</main>
      </body>
    </html>
  );
}
